### ISSUE TITLE
无法捐赠，停更了么？

### ISSUE THREAD

**Issue by Dopen9233** [Soptq/Medianotification_bug#9]
Description:
---

我也是个程序猿，支持一下

Device info:
---
<table>
<tr><td>App version</td><td>v1.0-22-gaa72cda</td></tr>
<tr><td>App version code</td><td>133</td></tr>
<tr><td>Android build version</td><td>V10.2.1.0.OCACNFK</td></tr>
<tr><td>Android release version</td><td>8.0.0</td></tr>
<tr><td>Android SDK version</td><td>26</td></tr>
<tr><td>Android build ID</td><td>OPR1</td></tr>
<tr><td>Device brand</td><td>Xiaomi</td></tr>
<tr><td>Device manufacturer</td><td>Xiaomi</td></tr>
<tr><td>Device name</td><td>sagit</td></tr>
<tr><td>Device model</td><td>MI 6</td></tr>
<tr><td>Device product name</td><td>sagit</td></tr>
<tr><td>Device hardware name</td><td>qcom</td></tr>
<tr><td>ABIs</td><td>[arm64-v8a, armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (32bit)</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (64bit)</td><td>[arm64-v8a]</td></tr>
</table>

Extra info:
---
<table>
<tr><td>Info 1</td><td>logcat</td></tr>
<tr><td>Info 2</td><td>true</td></tr>
</table>

**Comment by Soptq** [comment]
首先，感谢您对这个 APP 的支持。今天早上起床后看到您的 issue 我还是有点感动的，我的 APP 现在都还有人用啊～～。
然后是回答问题：

### 是的，MediaNotification 已经停更了

一开始开发这款 APP 的缘由是我当时的手机，索尼 Z5，不支持升级到安卓8，也就不支持安卓8风格的状态栏。于是我就自己搞了个 APP 来仿相关功能。后来换手机了后，也就不在开发了。

在我停更前 MediaNotification 就已经完全开源，若您有有相关基础的话，可以在我的代码上新增功能，修改bug，构建属于自己的版本。

### 再一次感谢！

最后，再一次感谢您使用我曾经做的 APP。捐赠是不可能的，我都没有维护了哪还有脸接受捐赠，您的话已经让我很开心了。
